use_frameworks!

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true,
         :warn_for_multiple_pod_sources => false,
         :deterministic_uuids => false

platform :ios, '13.0'

target 'QingLi_Example' do
  pod 'QingLi', :path => '../'
  pod 'SSZipArchive'
  pod 'Bolts'
  pod 'Masonry'
  pod 'BlocksKit'
  pod 'MJExtension'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'SDWebImage'
  pod 'QMUIKit'
  
  
  target 'QingLi_Tests' do
    inherit! :search_paths

    
    
    
    
  end
end


# post_install 钩子
post_install do |installer|
  if installer.project
    installer.project.targets.each do |target|
      target.build_configurations.each do |config|
        # 设置所有子库的默认部署目标
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        puts "IPHONEOS_DEPLOYMENT_TARGET = 13."
      end
    end
  else
    puts "Warning: pods_project is nil. Skipping post_install configuration."
  end
end
